spring:
  datasource:
    url: jdbc:mysql://localhost:3306/groceries
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret-key: "your-secret-key"
  expiration: 86000000                     # 15 minutes for access token
  refresh-expiration: 604800000          # 7 days for refresh token

